INCLUDE(FindPackageHandleStandardArgs)

IF(NOT ZMQ_ROOT)
  SET(ZMQ_ROOT "/usr")
ENDIF()

FIND_PATH(ZMQ_INCLUDE_DIRS
  NAMES zmq.h
  PATHS "${ZMQ_ROOT}"
  PATH_SUFFIXES include)

FIND_LIBRARY(ZMQ_LIBRARIES
  NAMES zmq
  PATHS "${ZMQ_ROOT}"
  PATH_SUFFIXES lib)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZMQ REQUIRED_VARS
  ZMQ_LIBRARIES
  ZMQ_INCLUDE_DIRS)

IF(ZMQ_FOUND)
  SET(ZMQ_LIBRARY_DIRS "${ZMQ_ROOT}/lib")
ENDIF()

MARK_AS_ADVANCED(ZMQ_INCLUDE_DIRS)
